image_dir: "../data/combined_reannotated/valid/images"
label_dir: "../data/combined_reannotated/valid/labels"
data_config: "../data/combined_reannotated/data.yaml"

model_id: "IDEA-Research/grounding-dino-base"
conf_thresh: 0.1

experiment_name: "VLM Inference"